# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import current_pb2 as current__pb2


class ChatBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.stream_unary(
                '/ChatBot/send',
                request_serializer=current__pb2.Message.SerializeToString,
                response_deserializer=current__pb2.Empty.FromString,
                )
        self.receive = channel.unary_stream(
                '/ChatBot/receive',
                request_serializer=current__pb2.Empty.SerializeToString,
                response_deserializer=current__pb2.Message.FromString,
                )
        self.login = channel.unary_unary(
                '/ChatBot/login',
                request_serializer=current__pb2.User.SerializeToString,
                response_deserializer=current__pb2.Empty.FromString,
                )


class ChatBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.stream_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=current__pb2.Message.FromString,
                    response_serializer=current__pb2.Empty.SerializeToString,
            ),
            'receive': grpc.unary_stream_rpc_method_handler(
                    servicer.receive,
                    request_deserializer=current__pb2.Empty.FromString,
                    response_serializer=current__pb2.Message.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=current__pb2.User.FromString,
                    response_serializer=current__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ChatBot/send',
            current__pb2.Message.SerializeToString,
            current__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatBot/receive',
            current__pb2.Empty.SerializeToString,
            current__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatBot/login',
            current__pb2.User.SerializeToString,
            current__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
